package com.knowledgebase.integration;

import com.knowledgebase.domain.model.GlobalRole;
import com.knowledgebase.support.IntegrationTestBase;
import org.junit.jupiter.api.Test;

import static org.hamcrest.Matchers.hasSize;
import static org.hamcrest.Matchers.is;
import static org.springframework.http.MediaType.APPLICATION_JSON;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.put;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

class DocumentFilterIntegrationTest extends IntegrationTestBase {

    @Test
    void listDocuments_statusFilter_returnsOnlyMatchingStatus() throws Exception {
        ensureDocumentsTable();
        persistUser("admin", "admin123", "admin@kb.local", GlobalRole.EDITOR, true);
        String adminJwt = loginAndGetJwt("admin", "admin123");
        long spaceId = createSpace(adminJwt, "Filter Space");

        long draftId = createDocument(adminJwt, spaceId, "Draft doc");
        long publishedId = createDocument(adminJwt, spaceId, "Published doc");
        publishDocument(adminJwt, publishedId);

        mockMvc.perform(get("/api/documents?status=Published&includeDeleted=true")
                        .cookie(jwtCookie(adminJwt)))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.content", hasSize(1)))
                .andExpect(jsonPath("$.content[0].id", is((int) publishedId)))
                .andExpect(jsonPath("$.content[0].status", is("PUBLISHED")));

        mockMvc.perform(get("/api/documents?status=Draft&includeDeleted=true")
                        .cookie(jwtCookie(adminJwt)))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.content", hasSize(1)))
                .andExpect(jsonPath("$.content[0].id", is((int) draftId)))
                .andExpect(jsonPath("$.content[0].status", is("DRAFT")));
    }

    @Test
    void listDocuments_spaceAndStatusFilters_useAndLogic() throws Exception {
        ensureDocumentsTable();
        persistUser("admin", "admin123", "admin@kb.local", GlobalRole.EDITOR, true);
        String adminJwt = loginAndGetJwt("admin", "admin123");
        long spaceA = createSpace(adminJwt, "Space A");
        long spaceB = createSpace(adminJwt, "Space B");

        long draftInA = createDocument(adminJwt, spaceA, "Draft in A");
        long publishedInA = createDocument(adminJwt, spaceA, "Published in A");
        publishDocument(adminJwt, publishedInA);
        long publishedInB = createDocument(adminJwt, spaceB, "Published in B");
        publishDocument(adminJwt, publishedInB);

        mockMvc.perform(get("/api/documents?spaceId=" + spaceA + "&status=Published&includeDeleted=true")
                        .cookie(jwtCookie(adminJwt)))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.content", hasSize(1)))
                .andExpect(jsonPath("$.content[0].id", is((int) publishedInA)));

        mockMvc.perform(get("/api/documents?spaceId=" + spaceA + "&status=Draft&includeDeleted=true")
                        .cookie(jwtCookie(adminJwt)))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.content", hasSize(1)))
                .andExpect(jsonPath("$.content[0].id", is((int) draftInA)));

        mockMvc.perform(get("/api/documents?spaceId=" + spaceB + "&status=Published&includeDeleted=true")
                        .cookie(jwtCookie(adminJwt)))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.content", hasSize(1)))
                .andExpect(jsonPath("$.content[0].id", is((int) publishedInB)));
    }

    private long createSpace(String jwt, String name) throws Exception {
        String response = mockMvc.perform(post("/api/admin/spaces")
                        .cookie(jwtCookie(jwt))
                        .contentType(APPLICATION_JSON)
                        .content("""
                                {"name":"%s","description":"desc"}
                                """.formatted(name)))
                .andExpect(status().isCreated())
                .andReturn()
                .getResponse()
                .getContentAsString();
        return Long.parseLong(response.replaceAll("(?s).*\\\"id\\\"\\s*:\\s*(\\d+).*", "$1"));
    }

    private void ensureDocumentsTable() {
        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS documents (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    title VARCHAR(500) NOT NULL,
                    git_file_path VARCHAR(500) NOT NULL,
                    status VARCHAR(20) NOT NULL,
                    author_id BIGINT NOT NULL,
                    space_id BIGINT NOT NULL,
                    template_id BIGINT,
                    parent_document_id BIGINT,
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    CONSTRAINT uq_documents_git_file_path UNIQUE (git_file_path)
                )
                """);
        jdbcTemplate.execute("DELETE FROM documents");
    }

    private long createDocument(String jwt, long spaceId, String title) throws Exception {
        String response = mockMvc.perform(post("/api/documents")
                        .cookie(jwtCookie(jwt))
                        .contentType(APPLICATION_JSON)
                        .content("""
                                {"title":"%s","content":"# test","spaceId":%d}
                                """.formatted(title, spaceId)))
                .andExpect(status().isCreated())
                .andReturn()
                .getResponse()
                .getContentAsString();

        return Long.parseLong(response.replaceAll("(?s).*\\\"id\\\"\\s*:\\s*(\\d+).*", "$1"));
    }

    private void publishDocument(String jwt, long documentId) throws Exception {
        mockMvc.perform(put("/api/documents/" + documentId)
                        .cookie(jwtCookie(jwt))
                        .contentType(APPLICATION_JSON)
                        .content("{\"status\":\"PUBLISHED\"}"))
                .andExpect(status().isOk());
    }
}
