package com.knowledgebase.integration;

import com.knowledgebase.domain.model.Document;
import com.knowledgebase.domain.model.GlobalRole;
import com.knowledgebase.domain.model.Space;
import com.knowledgebase.domain.model.User;
import com.knowledgebase.support.IntegrationTestBase;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertTrue;

class RequirementNumberGenerationIntegrationTest extends IntegrationTestBase {

    @Test
    void createDocumentFromTemplate_assignsSequentialRequirementNumbersPerSpaceAndTemplate() {
        User author = persistUser(uniqueLogin("editor"), "user123", "editor@kb.local", GlobalRole.EDITOR, false);
        createDocumentsTable();

        Long templateId = createRequirementTemplate();

        Space spaceA = spaceRepository.save(Space.create("Space A", "First space", author.getId()));
        Document firstDocument = documentService.createDocument("Doc A1", null, spaceA.getId(), null, author.getId(), templateId);
        String firstContent = documentService.getDocumentContent(firstDocument);

        assertTrue(firstContent.contains("REQ-001"));
        assertTrue(firstContent.contains("REQ-002"));

        Document secondDocument = documentService.createDocument("Doc A2", null, spaceA.getId(), null, author.getId(), templateId);
        String secondContent = documentService.getDocumentContent(secondDocument);

        assertTrue(secondContent.contains("REQ-003"));
        assertTrue(secondContent.contains("REQ-004"));

        Space spaceB = spaceRepository.save(Space.create("Space B", "Second space", author.getId()));
        Document thirdDocument = documentService.createDocument("Doc B1", null, spaceB.getId(), null, author.getId(), templateId);
        String thirdContent = documentService.getDocumentContent(thirdDocument);

        assertTrue(thirdContent.contains("REQ-001"));
        assertTrue(thirdContent.contains("REQ-002"));
    }

    private void createDocumentsTable() {
        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS documents (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    title VARCHAR(500) NOT NULL,
                    git_file_path VARCHAR(500) NOT NULL,
                    status VARCHAR(20) NOT NULL,
                    author_id BIGINT NOT NULL,
                    space_id BIGINT NOT NULL,
                    template_id BIGINT,
                    parent_document_id BIGINT,
                    created_at TIMESTAMP NOT NULL,
                    updated_at TIMESTAMP NOT NULL
                )
                """);
    }

    private Long createRequirementTemplate() {
        String templateName = uniqueLogin("requirement-template");
        String templateContent = """
            # Req

            | № | Name |
            |---|---|
            |   | A |
            |   | B |
            """;

        jdbcTemplate.update(
                """
                INSERT INTO templates (name, description, content, role, is_system, created_at, updated_at)
                VALUES (?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
                """,
                templateName,
                "Template for requirement numbering tests",
                templateContent,
                "Analyst",
                true
        );

        return jdbcTemplate.queryForObject(
                "SELECT id FROM templates WHERE name = ?",
                Long.class,
                templateName
        );
    }
}