package com.knowledgebase.integration;

import liquibase.Contexts;
import liquibase.LabelExpression;
import liquibase.Liquibase;
import liquibase.database.Database;
import liquibase.database.DatabaseFactory;
import liquibase.database.jvm.JdbcConnection;
import liquibase.resource.ClassLoaderResourceAccessor;
import org.junit.jupiter.api.Test;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

class SystemTemplateLiquibaseTest {

    @Test
    void systemTemplateMigrations_preserveMarkdownLineBreaksAfterRepairChangeSet() throws Exception {
        try (Connection connection = openConnection()) {
            createTemplatesTable(connection);

            applyChangeLog(connection, "db/changelog/changes/005-insert-system-templates.xml");
            applyChangeLog(connection, "db/changelog/changes/032-repair-system-template-newlines.xml");

            String content = loadTemplateContent(connection, "Описание архитектуры");
            assertTrue(content.contains("\n## Обзор системы\n"));
            assertTrue(content.contains("\n| Компонент | Технология | Версия |\n"));
            assertFalse(content.contains("Описание архитектуры ## Обзор системы"));
        }
    }

    @Test
    void repairSystemTemplateNewlines_updatesExistingSystemTemplatesOnly() throws Exception {
        try (Connection connection = openConnection()) {
            createTemplatesTable(connection);

            try (Statement statement = connection.createStatement()) {
                statement.executeUpdate("""
                        INSERT INTO templates (name, description, content, role, is_system, created_at, updated_at)
                        VALUES ('Описание архитектуры', 'Документирование структурных решений системы',
                                '# Описание архитектуры ## Обзор системы', 'Developer', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
                        """);
                statement.executeUpdate("""
                        INSERT INTO templates (name, description, content, role, is_system, created_at, updated_at)
                        VALUES ('Пользовательский шаблон', 'Не системный',
                                '# Custom ## Must stay flat', 'Developer', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
                        """);
            }

            applyChangeLog(connection, "db/changelog/changes/032-repair-system-template-newlines.xml");

            String repairedContent = loadTemplateContent(connection, "Описание архитектуры");
            String customContent = loadTemplateContent(connection, "Пользовательский шаблон");

            assertTrue(repairedContent.contains("\n## Обзор системы\n"));
            assertFalse(repairedContent.contains("Описание архитектуры ## Обзор системы"));
            assertTrue(customContent.contains("# Custom ## Must stay flat"));
        }
    }

    private Connection openConnection() throws Exception {
        String databaseName = "template_liquibase_" + UUID.randomUUID().toString().replace("-", "");
        return DriverManager.getConnection(
                "jdbc:h2:mem:" + databaseName + ";MODE=PostgreSQL;DB_CLOSE_DELAY=-1",
                "sa",
                ""
        );
    }

    private void createTemplatesTable(Connection connection) throws Exception {
        try (Statement statement = connection.createStatement()) {
            statement.executeUpdate("""
                    CREATE TABLE templates (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR(200) NOT NULL UNIQUE,
                        description TEXT,
                        content TEXT NOT NULL,
                        role VARCHAR(20) NOT NULL,
                        is_system BOOLEAN NOT NULL DEFAULT TRUE,
                        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                        updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
                    )
                    """);
        }
    }

    private void applyChangeLog(Connection connection, String changeLogPath) throws Exception {
        Database database = DatabaseFactory.getInstance()
                .findCorrectDatabaseImplementation(new JdbcConnection(connection));
        Liquibase liquibase = new Liquibase(changeLogPath, new ClassLoaderResourceAccessor(), database);
        liquibase.update(new Contexts(), new LabelExpression());
    }

    private String loadTemplateContent(Connection connection, String name) throws Exception {
        try (var statement = connection.prepareStatement("SELECT content FROM templates WHERE name = ?")) {
            statement.setString(1, name);
            try (ResultSet resultSet = statement.executeQuery()) {
                if (!resultSet.next()) {
                    throw new AssertionError("Template not found: " + name);
                }
                return resultSet.getString(1);
            }
        }
    }
}
