package com.knowledgebase.integration;

import com.knowledgebase.domain.model.Document;
import com.knowledgebase.domain.model.GlobalRole;
import com.knowledgebase.domain.model.Space;
import com.knowledgebase.domain.model.User;
import com.knowledgebase.support.IntegrationTestBase;
import org.junit.jupiter.api.Test;
import org.springframework.core.io.ClassPathResource;

import java.io.IOException;
import java.nio.charset.StandardCharsets;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

class SystemTemplateContentIntegrationTest extends IntegrationTestBase {

    @Test
    void systemTemplateResource_preservesMarkdownLineBreaks() throws IOException {
        String content = readTemplateResource("architecture-description.md");

        assertTrue(content.contains("\n## Обзор системы\n"));
        assertTrue(content.contains("\n| Компонент | Технология | Версия |\n"));
        assertFalse(content.contains("Описание архитектуры ## Обзор системы"));
    }

    @Test
    void createDocumentFromSystemRequirementsTemplate_preservesLineBreaksAndNumbersRequirements() throws IOException {
        User author = persistUser(uniqueLogin("editor"), "user123", "editor@kb.local", GlobalRole.EDITOR, false);
        createDocumentsTable();
        Long templateId = insertSystemTemplate(
                "Требования к системе",
                "Функциональные и нефункциональные требования",
                readTemplateResource("system-requirements.md"),
                "Analyst"
        );

        Space space = spaceRepository.save(Space.create("Template Space", "System template test", author.getId()));
        Document document = documentService.createDocument("Requirements Doc", null, space.getId(), null, author.getId(), templateId);

        String savedContent = documentService.getDocumentContent(document);

        assertTrue(savedContent.contains("\n## Функциональные требования\n"));
        assertTrue(savedContent.contains("\n| REQ-001 |"));
        assertTrue(savedContent.contains("\n| REQ-002 |"));
        assertFalse(savedContent.contains("# Требования к системе ## Информация о документе"));
    }

    private String readTemplateResource(String filename) throws IOException {
        ClassPathResource resource = new ClassPathResource("db/changelog/templates/" + filename);
        return resource.getContentAsString(StandardCharsets.UTF_8);
    }

    private Long insertSystemTemplate(String name, String description, String content, String role) {
        jdbcTemplate.update(
                """
                INSERT INTO templates (name, description, content, role, is_system, created_at, updated_at)
                VALUES (?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
                """,
                name,
                description,
                content,
                role,
                true
        );

        return jdbcTemplate.queryForObject(
                "SELECT id FROM templates WHERE name = ?",
                Long.class,
                name
        );
    }

    private void createDocumentsTable() {
        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS documents (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    title VARCHAR(500) NOT NULL,
                    git_file_path VARCHAR(500) NOT NULL,
                    status VARCHAR(20) NOT NULL,
                    author_id BIGINT NOT NULL,
                    space_id BIGINT NOT NULL,
                    template_id BIGINT,
                    parent_document_id BIGINT,
                    created_at TIMESTAMP NOT NULL,
                    updated_at TIMESTAMP NOT NULL
                )
                """);
    }
}
